[package]
name = "kushi"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "A queue built for the Dango Music Player and Oden Music Bot"
homepage = "https://github.com/Dangoware/kushi-queue"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Dangoware/kushi-queue"
keywords = ["queue","music","vec", "dmp"]
categories = ["data-structures"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.61"