// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { URI } from "./URI";

export type AlbumArt = { "Embedded": number } | { "External": URI };
