// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigLibrary } from "./ConfigLibrary";

export type ConfigLibraries = { default_library: string, library_folder: string, libraries: Array<ConfigLibrary>, };
