// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumArt } from "./AlbumArt";
import type { BannedType } from "./BannedType";
import type { InternalTag } from "./InternalTag";
import type { URI } from "./URI";

/**
 * Stores information about a single song
 */
export type Song = { location: Array<URI>, uuid: string, plays: number, skips: number, favorited: boolean, banned: BannedType | null, rating: number | null, 
/**
 * MIME type
 */
format: string | null, duration: number, play_time: number, last_played: number, date_added: number, date_modified: number, album_art: Array<AlbumArt>, tags: any, internal_tags: Array<InternalTag>, };
